version: '3.1'
services:
  reading-mlk:
    build: .
    restart: unless-stopped
    ports:
      -"3000-3000"
    volumes:
      -.:/app
    environment:
      - NODE_ENV=development
    command: npm run dev
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - $POSTGRES_PORT:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    driver: local