version: '3.1'


services:


 db:
   image: postgres
   restart: unless-stopped
   environment:
<<<<<<< Updated upstream
     - POSTGRES_USER = postgres
     - POSTGRES_PASSWORD = postgres
=======
     POSTGRES_USER = postgres
     POSTGRES_PASSWORD = postgres
>>>>>>> Stashed changes
   ports:
     - $POSTGRES_PORT:5432
   volumes:
     - postgres-data:/var/lib/postgresql/data


 adminer:
   image: adminer
   restart: unless-stopped
   ports:
     - 8080:8080
 volumes:
   postgres-data:
   driver: local