version: '3.1'


services:


 db:
   image: postgres
   restart: unless-stopped
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - DB_NAME=database1
   ports:
     - $POSTGRES_PORT:5432
   volumes:
     - postgres-data:/var/lib/postgresql/data

 adminer:
   image: adminer
   restart: unless-stopped
  
   ports:
     - 8080:80
  
volumes:
  postgres-data:
    driver: local