allowBuilds:
  '@parcel/watcher': set this to true or false
  '@prisma/engines': set this to true or false
  better-sqlite3: set this to true or false
  esbuild: set this to true or false
  prisma: set this to true or false
  sharp: set this to true or false
  vue-demi: set this to true or false
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/engines'
  - better-sqlite3
  - esbuild
  - prisma
  - vue-demi
