name: Auto Build Check

on:
  pull_request:
    branches:
      - main


jobs:
  buildCheck:
    runs-on: ubuntu-24.04-arm

    strategy:
      matrix:
        node-version: [24.x]
    
    steps:
    - uses: actions/checkout@v6

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies from Package-Lock
    - run: npm ci

    - name: Generate Prisma Client
    - run: npx prisma generate

    - name: Build Project
    - run: npm run build

